### ISSUE TITLE
Phone unresponsible before alarm clock time

### ISSUE THREAD

**Issue by pisajew** [mudita/MuditaOS#3823] opened 2022-05-11 03:15 UTC
# 🐛 Bug report

## 📝 Description

I left my phone connected with usb cable to a PC for charging. Keyboard was disabled and phone mode was set to do not disturb. 
Phone unresponsive when alarm clock should fire. Constantly vibrating, emitting weird noises.
## 👍 Expected behavior

Phone should play alarm sound as normal and remain responsive to user interaction (i.e. it should be possible to unlock the keyboard and turn off the alarm)

## 👎 Current behavior

When alarm time came the phone activated vibration motor and started emmitting noises (like playing back the alarm music but without meeting timing deadline for filling playback buffer maybe because of highly overloaded CPU). The keyboard is unresponsive. Display stucked at clock showing alarm time minus one minute. The phone is not responding to the keyboard, I see no obivous way to restart it / turin it off. Eventually, 1..2 minutes after I removed SIM card, the phone did turn off the buzzer and stopped making sounds. The keyboard was still unresponsive. When I tried to remove battery it finally rebooted. The whole thing was like 12 minutes.

## 🔬 Minimal reproduction

I only had this once, so I'm not sure how likely it is to reproduce it in repeatable way. My steps were:

1. Set up the alarm to trigger after several hours (it was in the evening and alarm was set to trigger in the morning).
2. Leave phone connected to the USB (on a PC) for charging
3. Be close to the phone 1..2 minutes before alarm should trigger so that you can observe the start of described problem.

Issues that don't have enough info and can't be reproduced will be closed. Yea. Go ahead and close it.

## 🔍 Provide logs

No logs for this problem. I have connected the Pure to Mudita Center as soon as I got it restarted. It usually prompts me to send crash logs to support, but there was no such prompt this time. Apparently described situation was not interpreted as a crash but rather some form of ordinary restart (due to my attempt to remove the battery?).

## 🌍 Your operating system and MuditaOS version
1.2.0
## 🤔 Anything else relevant?
The behaviour of the system was like just some process would enter an infinite loop, consuming most of the CPU. The others (i.e. alarm playback) wouldn't get enough of CPU time to meet real time deadlines which made phone unresponsive and caused it to play like a single playback frame every few seconds.

**Comment by SP2FET** [comment] 2022-05-16 10:17
Could you please fill up the template as it's supposed to be? And if it's possible, please send logs via Mudita Center. This template has its purpose - we are not able to reproduce some bugs when the description is not complete.
Saying so, once again, please send logs via Mudita Center and paste here your serial number to be able to distinguish your logs from the rest. We'll try to reproduce the bug on our own either way.

**Comment by esope** [comment] 2022-05-16 11:33
I experienced the same bug.
It happens (sometimes) when the phone is charging and (I guess) when it remains plugged for a long time while the battery is fully charged (like when you plug the phone before getting to sleep, and the bug happens the next morning).
The sound of the alarm stutters, as if the CPU was overloaded. Some process getting crazy, or some infinte loop, maybe ?
This bug is very annoying.

**Comment by adamgas** [comment] 2022-05-20 05:56
same - after second snooze, the third alarm didn't went off normally - it just buzzed constantly, no response from keyboard clicks, self-resetted after few minutes

**Comment by pholat** [comment] 2022-05-23 10:17
@esope @adamgas thanks! this is the start we could work with!
Internal bug reference: https://appnroll.atlassian.net/browse/MOS-503
@pisajew would you be so kind as to properly fill in the issue?

**Comment by Maciej-Mudita** [comment] 2022-06-24 07:31
@pisajew @esope @adamgas the problem will be fixed in the new version 1.3.0

**Closed** 2022-06-24 07:32 UTC
