### ISSUE TITLE
Incoming call while editing contact freezes and reboots Pure

### ISSUE THREAD

**Issue by rawzen** [mudita/MuditaOS#3657] opened 2022-03-18 21:41 UTC
1. Pure is set to DO NOT DISTURB mode. (The bug won't reproduce for me in CONNECTED mode.)
2. Enter editing mode of any contact.
3. Move focus to another field in the contact. (The bug won't reproduce for me if I don't move focus.)
4. Make a call to Pure.
5. The call does not come through.
6. Pure freezes, no buttons are responsive.
7. After a rather short press on the hang up button the phone reboots by itself.

**Comment by SP2FET** [comment] 2022-03-21 07:36
Hi, which firmware version are you using? The latest one (1.1.6)?

**Comment by rawzen** [comment] 2022-03-21 07:41
Yes. It is version 1.1.6.

mån 21 mars 2022 kl. 08:36 skrev Bartosz Cichocki ***@***.***

**Comment by SP2FET** [comment] 2022-06-13 10:59
Unfortunately, we can't reproduce it on the latest release. Closing right now, if the issue persists, please reopen it.

**Closed by SP2FET** 2022-06-13 10:59 UTC
