### ISSUE TITLE
Missed calls in log still bold (flag "unseen")

### ISSUE THREAD

**Issue by czalaviek** [mudita/MuditaOS#3555] opened 2022-02-06 22:14 UTC
# 🐛 Bug report

## 📝 Description

I've reviewed all my missed calls in call log, but they are still bold

## 👍 Expected behavior

All call log position should be unbolded alter review.

## 👎 Current behavior

Reviewed all missed calls in call log are still bold

## 🌍 Your operating system and MuditaOS version
1.1.6

**Comment by SP2FET** [comment] 2022-02-09 11:15
Hi,
The issue indeed exists, it is probably related to the issue you mentioned before and we're on track to fix it!

**Comment by SP2FET** [comment] 2022-02-10 08:27
I've created a separate ticket for this bug:
https://appnroll.atlassian.net/browse/MOS-158

**Comment by SP2FET** [comment] 2022-02-11 07:57
Hi, I've got some info that this is not a bug, it's a feature. The bolded entries meant to be the missed calls - that's the way it's designed. If we'll got more complaints about this, it will be reworked then.

**Comment by mjan-dev** [comment] 2022-02-14 11:38
@czalaviek I'm closing this issue as it has been reviewed by the team and this behavior is indeed as designed. As @SP2FET mentioned, we will gladly redesign it if more complaints about this feature arises. Thanks for reporting.

**Closed by mjan-dev** 2022-02-14 11:38 UTC
Labels: community
